version: "3.9"

# persisting db data in volume
volumes:
  db-vol:

services:

  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      # this is the name of our database, that will be created automatically
      MYSQL_DATABASE: loadmore
    restart: unless-stopped
    volumes:
      - db-vol:/var/lib/mysql
    ports:
      - "3306:3306"